---

- include: java-install.yml

- name: Importing the Elasticsearch public GPG key into rpm
  rpm_key:
    state: absent
    key: "{{ elasticsearch_rpm_key }}"
  become: yes

- name: Creating a new yum repository file for Elasticsearch
  template: 
    src: elasticsearch.repo.j2
    dest: "/etc/yum.repos.d/{{ elasticsearch_repo_name }}"
  become: yes

- name: Installing Elasticsearch pkg from repo
  yum: 
    name: "{{ elasticsearch_pkg_name }}"
    state: present
  become: yes

- name: Configuring Elasticsearch
  template:
    src: elasticsearch.yml.j2
    dest: "/etc/elasticsearch/{{ elasticsearch_fileconf_name }}"
  become: yes

- name: Configure elasticsearch log path
  template:
    src: logging.yml.j2
    dest: "/etc/elasticsearch/{{ elasticsearch_logconf_name }}"
  become: yes

- name: Create log path if not exist
  file: 
    path: "{{ elasticsearch_log_path }}"
    owner: elasticsearch 
    group: elasticsearch
    state: directory
    mode: 0750
  become: yes

- name: Configuring elasticsearch.service in systemd/system
  template:
    src: elasticsearch.service.j2
    dest: /lib/systemd/system/elasticsearch.service
  become: yes

- name: Reload systemd
  become: yes
  command: systemctl daemon-reload

- name: Logrotate configuration file
  template:
    src: logrotate.elasticsearch.j2
    dest: /etc/logrotate.d/elasticsearch
  become: yes	

- name: Restarting Elasticsearch
  service:
    name: "{{ elasticsearch_service_name }}"
    state: restarted 
    enabled: yes
  become: yes
