---
- name: Importing the Elasticsearch public GPG key into rpm
  rpm_key:
    state: absent
    key: "{{ elasticsearch_rpm_key }}"
  become: yes

- name: Creating a new yum repository file for Kibana
  template:
    src: kibana.repo.j2
    dest: "/etc/yum.repos.d/{{ kibana_repo_name }}"
  become: yes

- name: Installing Kibana package from repo
  yum: 
    name: "{{ kibana_pkg_name }}"
    state: present
  become: yes

- name: Configuring Kibana
  template:
    src: kibana.yml.j2
    dest: "/opt/kibana/config/{{ kibana_fileconf_name }}"
  become: yes

- name: Create log path if not exist
  file: 
    path: "{{ kibana_directorylogpath_name }}"
    owner: kibana 
    group: root
    state: directory
    mode: 0750
  become: yes

- name: Configuring kibana.service in systemd/system
  template:
    src: kibana.service.j2
    dest: /lib/systemd/system/kibana.service
  become: yes

- name: Reload systemd
  become: yes
  command: systemctl daemon-reload


- name: Logrotate log file
  template:
    src: logrotate.kibana.j2
    dest: /etc/logrotate.d/kibana
  become: yes

- name: Restarted Kibana
  service: 
    name: "{{ kibana_service_name }}"
    state: restarted 
    enabled: yes
  become: yes
